name: CI

on:
  push: { branches: [main] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with: { cache: "npm", node-version: "16" }
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
      - run: npm run lint
